---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Apache2
    apt:
      name: apache2
      state: present

  # this fails
  - name: Ensure that apache2 is started
    service: name=apache2 state=started

- hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - geerlingguy.docker

- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Make sure Docker service is running
    systemd:
      state: started
      name: docker